### ISSUE TITLE
Problem: Mismatch Architecture of Kgw File on Mac Device

### ISSUE THREAD

**Issue by melianapang** [trufnetwork/node#712]
sub of: 
- #674 

When we run `task compose-dev`, the task of `kwil-binaries-dev` will be run first to download `kgw` file to `.build` local directory. 
This makes `kgw` file will be compatible with host's architecture (in my case is darwin-arm64).
Later I found that this local `kgw` file will be copied to the container to run `kwil-gateway` service (`dev-gateway-compose.yml`).
```
    volumes:
      - type: bind
        # bind the file to the container
        source: ../../.build/kgw
        target: /app/kgw
```
This will cause micmatch architecture, the `kwil-gateway` container and `nginx` container will be exited.
Other than that, macOS has different way to trust local certification for `nginx` service.

So, I proposed to:
1.  Update dropbox url based on supported OS and architecture.
2. Copy the download binaries script to the container, then execute it.
3. Remove `type: bind` in `kwil-gateway` service.
4. Remove `deps: [ kwil-binaries-dev ]` from `task compose-dev`.
5. (Optional) Remove `kwil-binaries-dev` task.
6. Add new `task` to trust local certs for development for macOS.

Is there any opinion or suggestion regarding this issue?
